baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "GeoTIFF.io"
publishDir = "docs"
theme = "hugo-universal-theme"

# [menu]

# # Main menu

# [[menu.main]]
#     name = "Home"
#     url  = "/"
#     weight = 1

# [[menu.main]]
#     name = "Gallery"
#     url  = "/gallery/"
#     weight = 2

# [[params.menu]]
#   name = "Home"
#   url = "/"
#   weight = 1

# [[params.menu]]
#   name = "Gallery"
#   url = "/gallery/"
#   weight = 2

[params]
  style = "turquoise"
  viewMorePostLink = "/gallery/"
  logo = "images/logo.png"

[params.features]
  enable = true

[params.carousel]
  enable = true

[params.testimonials]
  enable = true
  title = "Examples"
  subtitle = "Below are examples of GeoTIFF.io in action"

# [params.recent_posts]
#   enable = true
#   title = "Examples"
#   subtitle = "Below are examples of GeoTIFF.io in action:"
